### PR TITLE
changes to allow compiling on FreeBSD

### PR DESCRIPTION
**Pull request by trapexit**

### CODE REVIEW

**Comment by zofrex** [comment]
This is awesome! Thank you!

**Comment by trapexit** [comment]
No problem. I'll probably release new version in the next day so.

**Comment by zofrex** [comment]
Awesome :)

It would be a lot easier for FreeBSD users to install and upgrade mergerfs if a "port" (FreeBSD parlance for package, more or less) existed. Is that something you'd be interested in doing?

**Comment by trapexit** [comment]
I'm not familiar with FreeBSD ports, how they are maintained, etc. Best if someone in that community handled it. If it's something I can host then I'd be happy to own the repo but not sure I can help otherwise.

**Comment by zofrex** [comment]
Alright, I'll take a shot at that myself then. Thanks again!

**Pull request merged**
