### PR TITLE
Makefile: don't force -g, respect CPPFLAGS, don't require `which`

### PR DESCRIPTION
**Pull request by ahippo**
Please, find several Makefile fixes, which address some of the issues preventing [1] inclusion of mergerfs into Gentoo.

[1] https://github.com/gentoo/gentoo/pull/9544#issuecomment-414146058

@mgorny, please, feel free to take a look to make sure we're on the right track.

### CODE REVIEW

**Comment by trapexit** [comment]
* which: was done due to some odd build environment I was targeting. It's been a few years and I can't recall the specifics but its fine to change and if I run into the problem can work around it some other way.
* -g: Was probably accidental. Just remove it.
* flags: Should change CFLAGS to CXXFLAGS and put the cpp flags into CPPFLAGS

**Comment by ahippo** [comment]
> * which: was done due to some odd build environment I was targeting. It's been a few years and I can't recall the specifics but its fine to change and if I run into the problem can work around it some other way.

Hm.
But shouldn't proper `PATH` have solved it?
Or the `PATH` was sanitized, and the build wasn't picking up one of the tools installed to a non-standard directory?

> * -g: Was probably accidental. Just remove it.

RPM/DEB might need it to produce debuginfo packages, right?
I don't think, `-g` hurts under `OPTS`, so I can leave it there.

> * flags: Should change CFLAGS to CXXFLAGS

Sure, will do.
Originally, I wanted to change that too, but checked that there is no C vs C++ mix, and that CFLAGS are used solely for C++ code, so left it alone.
Will fix it.

> and put the cpp flags into CPPFLAGS

Good point.
Let me do that.

**Comment by ahippo** [comment]
I apologize for effectively abandoning the pull request.
(although I did plan to address your comments and refresh it)
My family has expanded recently, so that uses up all my spare time. :)

Just for the future reference, this pull request was incorporated into 6de8e4471c9338b36e84b575d4775181f0643513.

**Comment by trapexit** [comment]
Not a problem. Ive been doing some other cleanup and refactoring so decided to do this stuff too.

**Comment by trapexit** [comment]
And... Congrats!

**Comment by ahippo** [comment]
> Not a problem. Ive been doing some other cleanup and refactoring so decided to do this stuff too.

Cool.
Right, makes sense.

> And... Congrats!

Thank you! :)

**Pull request closed without merging**
