### PR TITLE
replace libfuse's autoconf with makefile and ecfd

### PR DESCRIPTION
**Pull request by trapexit**

### CODE REVIEW

**Comment by GitHubGeek** [comment]
Hello @trapexit , thanks for this great FS!

FYI, this PR broke `make deb` - changelog was not created

```
 dpkg-source -b mergerfs
tail: cannot open 'mergerfs/debian/changelog' for reading: No such file or directory
dpkg-source: error: tail of mergerfs/debian/changelog subprocess returned exit status 1
dpkg-buildpackage: error: dpkg-source -b mergerfs subprocess returned exit status 1
Makefile:197: recipe for target 'deb' failed
make: *** [deb] Error 1
```

**Comment by trapexit** [comment]
Thanks. I'll take a look. I should probably add make deb to Travis 😊

**Comment by ahippo** [comment]
@trapexit , this removed support for building with external libfuse, right?
Was this intentional?
Ability to build with external libfuse was an important requirement to get included into distros.

**Comment by trapexit** [comment]
Not this alone but yes.

My recent enhancements aren't possible with the existing versions of libfuse. My options were to write my own userland fuse library, fully vendor it, or write increasingly awkward code to work around libfuse and support multiple major versions of libfuse, or completely rewrite mergerfs and hope some of my changes could be upstreamed. None of these are fun but only one is practical at the moment.

**Comment by trapexit** [comment]
I don't mean this to sound rude but ultimately I have to put the interests of the project before packagers. There are exceptions for embedded code and mergerfs should fit into those. ntfs-3g is apparently given this exception.

```
$ ntfs-3g
ntfs-3g: No device is specified.

ntfs-3g 2017.3.23 integrated FUSE 28 - Third Generation NTFS Driver
                Configuration type 7, XATTRS are on, POSIX ACLS are on
...
```

**Comment by ahippo** [comment]
> Not this alone but yes.
> 
> My recent enhancements aren't possible with the existing versions of libfuse. My options were to write my own userland fuse library, fully vendor it, or write increasingly awkward code to work around libfuse and support multiple major versions of libfuse, or completely rewrite mergerfs and hope some of my changes could be upstreamed. None of these are fun but only one is practical at the moment.

I see.
It's a pity that merging your changes upstream is not a viable option at this moment,
especially given that there is libfuse-3.x now, which is being actively developed.

> I don't mean this to sound rude but ultimately I have to put the interests of the project before packagers. There are exceptions for embedded code and mergerfs should fit into those. ntfs-3g is apparently given this exception.
> 
> ```
> $ ntfs-3g
> ntfs-3g: No device is specified.
> 
> ntfs-3g 2017.3.23 integrated FUSE 28 - Third Generation NTFS Driver
>                 Configuration type 7, XATTRS are on, POSIX ACLS are on
> ...
> ```

It's maybe possible to argue with distro guys about internal libfuse, but having support for external libfuse could have been an easier way in.

Also, on Gentoo you _can_ build ntfs-3g with external libfuse, but with certain limitations.
(internal libfuse has to be used for unprivileged mounting to work)
```
$ ntfs-3g
ntfs-3g: No device is specified.

ntfs-3g 2017.3.23 external FUSE 29 - Third Generation NTFS Driver
                Configuration type 7, XATTRS are on, POSIX ACLS are on
...
```
In a similar way, mergerfs could have been built with external libfuse, but without threading support.

**Comment by trapexit** [comment]
It's not just threading. It's dynamic timeout values. It's fixing the broken ioctl calls. It's trying to work around the fuse module not providing file handles when it should and libfuse not providing a reasonable way to address it with the high level API. These all required changes to the high level API. Upstream won't be making breaking API changes. Though they may consider additional APIs that have priority over the old ones but it'd be very ugly.

Some of the things I've done could be addressed if I rewrote everything for the low level API. That's a lot of work. I've ready embedded the library for other reasons so it'd be silly to spend all the time rewriting code rather than tweaking the high level api. To build against system libfuse would require having two separate sets of code to mange the API differences with two separate sets of functionally is not something I'm interested in having. That's a lot of work and confuses users.

Distros have old versions of mergerfs and libfuse. I have to build my own packages else be shackled by their long release schedules. Even if I got everything I wanted upstream today it'd take forever to get into the most popular distros. I'd still need to do all the work I do today.

Provide me with a reasonable alternative and I'm happy to consider it.

The options as I see it are
1. entirely rewriting mergerfs for low level api. 
2. Fork libfuse publicly. 
3. Fork libfuse privately. 
4. Writing my own libfuse replacement. 
5. Making mergerfs build against 3 separate libraries with separate features for critical behaviors.
6. Tell users I won't support them and focus on one libfuse version.

Forking privately is the easiest and most flexible and most appealing to my users. If distros don't take that as a good enough reason for exception then I don't know what to say. No one is offering a better solution.

**Comment by ahippo** [comment]
Oh, I see.
If there are so many differences between upstream and internal libfuse, then sure, supporting both is not an easy task.

Using low-level API or reimplementing libfuse sounds like duplicating a lot of effort, which already went into high-level libfuse API.

I agree that forking libfuse privately is the easiest option.
However, it would be great to let libfuse maintainers know that there are certain issue with the library.
Even if they don't fix the issues right away, but just acknowledge them, it might be an additional argument for distros.

It's kind of surprising that other projects using libfuse don't face similar issues that mergerfs does.
(although mergerfs is surely way more sophisticated than many of them)

**Comment by trapexit** [comment]
Since some of the issues are just limitations to the high level API which can't really be altered too much its of limited use to bring them up. The answer would be to use the low level API. They would have to do a libfuse4 or create a second, sepate high level API. Or they'd need some ugly code to figure out what behavior to do.

Other projects do run into these problems. They just accept the limitations or just use the low-level api. The hard_remove problem is well known but  only if you use high level API. The kernel itself is part of the problem making a proper fix impossible at the moment.

Had I known the limits of the HLAPI I'd have used the LLAPI but it's too late now. At this point I'd rather create a new library that's geared towards my use case. Tweaking libfuse is just a stopgap.

**Pull request merged**
