### PR TITLE
fix build against latest libattr

### PR DESCRIPTION
**Pull request by lordwelch**

### CODE REVIEW

**Comment by trapexit** [comment]
Won't this break on older versions?

**Comment by lordwelch** [comment]
Most definitely. I just wanted to put it here so that if someone comes looking they can see the one change that needs to be made.
Here is the commit in attr for reference
http://git.savannah.nongnu.org/cgit/attr.git/commit/?id=7921157890d07858d092f4003ca4c6bae9fd2c38

**Comment by ahippo** [comment]
> `<sys/xattr.h>`

At least on my Linux machine, `<sys/xattr.h>` is actually provided by glibc,
while `<attr/xattr.h>` is provided by libattr.
The Makefile checks for `attr/xattr.h`, not for `sys/xattr.h`, so it needs to be changed accrodingly.

I guess, the Makefile needs to define either `HAVE_SYS_XATTR_H`, or `HAVE_ATTR_XATTR_H`, or none of them depending on what's available.

**Comment by lordwelch** [comment]
I should have read the commit message. xattr.h has been a part of [glibc](https://sourceware.org/git/?p=glibc.git;a=commit;h=c0ad824e402c7afde1b46be1620c70107aa3eda9) since 2002 apparently this shouldn't break anything.

**Comment by lordwelch** [comment]
[freebsd](https://www.freebsd.org/cgi/man.cgi?query=extattr&format=html)
[netbsd](http://netbsd.gw.com/cgi-bin/man-cgi?extattr_get_fd+2+NetBSD-current)
the OSX build dosen't seem to be working based on CI and I can't find an official source but
[unix.com manpages for osx](https://www.unix.com/man-page/osx/2/getxattr/)

**Comment by ahippo** [comment]
@lordwelch, thank you for doing some research!
Please, note that on *BSD, the header is `sys/extattr.h`, not `sys/xattr.h`.

Actually, `mergerfs` doesn't link with `-lattr`, so it is already using xattr functions from libc.
`sys/xattr.h` seems to be present in glibc since version 2.3 (year 2002),
which predates Linux FUSE support (year 2005).

Depending on *BSD support desired (which is up to @trapexit),
it should be safe to simply change `attr/xattr.h` to `sys/xattr.h` as proposed,
or check for `sys/xattr.h` and `sys/extattr.h`.

I suppose, `libattr1-dev` and `libattr-devel` can be removed from the `Makefile`, `debian/control`, and `mergerfs.spec` regardless.

**Comment by ahippo** [comment]
> I'm happy to change things but on my Ubuntu 18.04 system sys/xattr.h only exists in libc6-dev-i386.

Looks like, on amd64, it's located under `/usr/include/x86_64-linux-gnu/sys/xattr.h`.
`/usr/include/sys/xattr.h` is a part of `libc6-dev-i386` package for amd64 and `libc6-dev-amd64` for i386.

I guess, `#include <sys/xattr.h>` should still work.

**Comment by trapexit** [comment]
I'm working on a patch for all this but ... it looks like extended attributes on the BSDs (at least FreeBSD) are a different API all together.

BSDs are barely supported and I'm not sure anyone is using mergerfs on them so for now xattr can be unsupported on them.

**Comment by ahippo** [comment]
Just for future reference, this was fixed in #515.

**Pull request closed without merging**
